version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
      - "8081:8081"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - signal-api
    environment:
      - NODE_ENV=production
    command: node src/index.js
    restart: always

  signal-api:
    image: bbernhard/signal-cli-rest-api:0.20.0
    ports:
      - "8080:8080"
    volumes:
      - ./data/signal:/home/.local/share/signal-cli
    environment:
      - WEBHOOK_URL=https://signal-api.yourdomain.com/v1/webhook
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: signal_user
      POSTGRES_PASSWORD: SignalSecurePass2023
      POSTGRES_DB: signal_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always

