version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - signal-api
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=signal_user
      - DB_PASSWORD=SignalSecurePass2023
      - DB_NAME=signal_db
    command: node src/index.js
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: signal_user
      POSTGRES_PASSWORD: SignalSecurePass2023
      POSTGRES_DB: signal_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  signal-api:
    image: bbernhard/signal-cli-rest-api:0.20.0
    ports:
      - "8080:8080"
    environment:
      - WEBHOOK_URL=http://backend:3000/v1/webhook
    volumes:
      - ./data/signal:/home/.local/share/signal-cli
    restart: always

volumes:
  signal-data:
  postgres-data:

